export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const DASHBOARD_COUNT = 'DASHBOARD_COUNT';
export const DASHBOARD_SALES_CHART = 'DASHBOARD_SALES_CHART';
export const DASHBOARD_CUSTOMER_GROWTH = 'DASHBOARD_CUSTOMER_GROWTH';

export const CUSTOMER_SAVE = 'CUSTOMER_SAVE';
export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
export const CUSTOMER_REMOVE = 'CUSTOMER_REMOVE';
export const CUSTOMER_VIEW = 'CUSTOMER_VIEW';
export const CUSTOMER_HISTORY = 'CUSTOMER_HISTORY';
export const CUSTOMER_DELETE_ALL = 'CUSTOMER_DELETE_ALL';

export const FAQ_SAVE = 'FAQ_SAVE';
export const FAQ_LIST = 'FAQ_LIST';
export const FAQ_UPDATE = 'FAQ_UPDATE';
export const FAQ_REMOVE = 'FAQ_REMOVE';
export const FAQ_VIEW = 'FAQ_VIEW';
export const FAQ_HISTORY = 'FAQ_HISTORY';
export const FAQ_DELETE_ALL = 'FAQ_DELETE_ALL';

export const CATEGORY_SAVE = 'CATEGORY_SAVE';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_REMOVE = 'CATEGORY_REMOVE';
export const CATEGORY_VIEW = 'CATEGORY_VIEW';
export const CATEGORY_HISTORY = 'CATEGORY_HISTORY';
export const CATEGORY_DELETE_ALL = 'CATEGORY_DELETE_ALL';
export const CATEGORY_IMAGE_UPLOAD = 'CATEGORY_IMAGE_UPLOAD';

export const SUBCATEGORY_SAVE = 'SUBCATEGORY_SAVE';
export const SUBCATEGORY_LIST = 'SUBCATEGORY_LIST';
export const SUBCATEGORY_UPDATE = 'SUBCATEGORY_UPDATE';
export const SUBCATEGORY_REMOVE = 'SUBCATEGORY_REMOVE';
export const SUBCATEGORY_VIEW = 'SUBCATEGORY_VIEW';
export const SUBCATEGORY_HISTORY = 'SUBCATEGORY_HISTORY';
export const SUBCATEGORY_DELETE_ALL = 'SUBCATEGORY_DELETE_ALL';

export const PROMOCODE_SAVE = 'PROMOCODE_SAVE';
export const PROMOCODE_LIST = 'PROMOCODE_LIST';
export const PROMOCODE_UPDATE = 'PROMOCODE_UPDATE';
export const PROMOCODE_REMOVE = 'PROMOCODE_REMOVE';
export const PROMOCODE_VIEW = 'PROMOCODE_VIEW';
export const PROMOCODE_HISTORY = 'PROMOCODE_HISTORY';
export const PROMOCODE_DELETE_ALL = 'PROMOCODE_DELETE_ALL';

export const QUERY_SAVE = 'QUERY_SAVE';
export const QUERY_LIST = 'QUERY_LIST';
export const QUERY_UPDATE = 'QUERY_UPDATE';
export const QUERY_REMOVE = 'QUERY_REMOVE';
export const QUERY_VIEW = 'QUERY_VIEW';
export const QUERY_HISTORY = 'QUERY_HISTORY';
export const QUERY_DELETE_ALL = 'QUERY_DELETE_ALL';

export const NOTIFICATION_SAVE = 'NOTIFICATION_SAVE';
export const NOTIFICATION_LIST = 'NOTIFICATION_LIST';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';
export const NOTIFICATION_VIEW = 'NOTIFICATION_VIEW';
export const NOTIFICATION_HISTORY = 'NOTIFICATION_HISTORY';
export const NOTIFICATION_DELETE_ALL = 'NOTIFICATION_DELETE_ALL';

export const SEARCH_USER_WITH_ROLE = 'SEARCH_USER_WITH_ROLE';

export const SERVICE_PROVIDER_SAVE = 'SERVICE_PROVIDER_SAVE';
export const SERVICE_PROVIDER_LIST = 'SERVICE_PROVIDER_LIST';
export const SERVICE_PROVIDER_UPDATE = 'SERVICE_PROVIDER_UPDATE';
export const SERVICE_PROVIDER_REMOVE = 'SERVICE_PROVIDER_REMOVE';
export const SERVICE_PROVIDER_VIEW = 'SERVICE_PROVIDER_VIEW';
export const SERVICE_PROVIDER_HISTORY = 'SERVICE_PROVIDER_HISTORY';
export const SERVICE_PROVIDER_DELETE_ALL = 'SERVICE_PROVIDER_DELETE_ALL';
export const SERVICE_PROVIDER_PROFILE_IMG_UPLOAD = 'SERVICE_PROVIDER_PROFILE_IMG_UPLOAD';
export const SERVICE_PROVIDER_USER_LIST = 'SERVICE_PROVIDER_USER_LIST';

export const SERVICE_REQUEST_SAVE = 'SERVICE_REQUEST_SAVE';
export const SERVICE_REQUEST_LIST = 'SERVICE_REQUEST_LIST';
export const SERVICE_REQUEST_UPDATE = 'SERVICE_REQUEST_UPDATE';
export const SERVICE_REQUEST_REMOVE = 'SERVICE_REQUEST_REMOVE';
export const SERVICE_REQUEST_VIEW = 'SERVICE_REQUEST_VIEW';
export const SERVICE_REQUEST_HISTORY = 'SERVICE_REQUEST_HISTORY';
export const SERVICE_REQUEST_DELETE_ALL = 'SERVICE_REQUEST_DELETE_ALL';
export const SERVICE_REQUEST_ADD_RESOLUTION = 'SERVICE_REQUEST_ADD_RESOLUTION';
export const SERVICE_REQUEST_PAYMENT = 'SERVICE_REQUEST_PAYMENT';

export const ROLES_SAVE = 'ROLES_SAVE';
export const ROLES_LIST = 'ROLES_LIST';
export const ROLES_UPDATE = 'ROLES_UPDATE';
export const ROLES_REMOVE = 'ROLES_REMOVE';
export const ROLE_VIEW = 'ROLE_VIEW';
export const ROLES_HISTORY = 'ROLES_HISTORY';
export const ROLES_DELETE_ALL = 'ROLES_DELETE_ALL';
export const ROLES_ACCESS_LEVEL = 'ROLES_ACCESS_LEVEL';

export const MATERIAL_SAVE = 'MATERIAL_SAVE';
export const MATERIAL_LIST = 'MATERIAL_LIST';
export const MATERIAL_VIEW = 'MATERIAL_VIEW';
export const MATERIAL_EDIT = 'MATERIAL_EDIT';
export const MATERIAL_HISTORY = 'MATERIAL_HISTORY';
export const MATERIAL_REMOVE = 'MATERIAL_REMOVE';
export const MATERIAL_DELETE_ALL = 'MATERIAL_DELETE_ALL';
export const SUB_CATEGORY_LIST = "SUB_CATEGORY_LIST";

export const ACTIVE_TIME_REPORT_LIST = 'ACTIVE_TIME_REPORT_LIST';
export const EARNING_REPORT_LIST = 'EARNING_REPORT_LIST';
export const EARNING_SERVICE_REPORT_LIST = 'EARNING_SERVICE_REPORT_LIST';

export const RESPONSE_TIME_REPORT_LIST = 'RESPONSE_TIME_REPORT_LIST';
export const RATING_REPORT_LIST = 'RATING_REPORT_LIST';
export const SERVICE_REQUEST_REPORT_LIST = 'SERVICE_REQUEST_REPORT_LIST';

export const GET_CITY = 'GET_CITY';

export const CONFIGURATION_LIST = 'CONFIGURATION_LIST';
export const CONFIGURATION_SAVED = 'CONFIGURATION_SAVED';
